services:
  theatricalplayersrefactoringkata.api:
    image: ${DOCKER_REGISTRY-}theatricalplayersrefactoringkataapi
    build:
      context: .
      dockerfile: TheatricalPlayersRefactoringKata.API/Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433" 
    volumes:
      - sqlvolume:/var/opt/mssql/data

volumes:
  sqlvolume: